// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbkqgzairobefrmfdkei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJia3FnemFpcm9iZWZybWZka2VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE5NzYyMzIsImV4cCI6MjA4NzU1MjIzMn0.EgtVsROoznd40srvcr21pcTFoiw-88GKSmKR0Hz7CFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
